language: c

dist: trusty

os:
- linux
- windows

before_install:
  - >
    if test "$TRAVIS_OS_NAME" = "windows"; then
      test -f C:/tools/msys64/msys2_shell.cmd && rm -rf C:/tools/msys64
      choco uninstall -y mingw
      choco upgrade --no-progress -y msys2
      export msys2='cmd //C SET MSYSTEM=MSYS& CHERE_INVOKING=1& C:\\tools\\msys64\\usr\\bash -li -c "\$@"'
      export mingw32='cmd //C SET MSYSTEM=MINGW32& CHERE_INVOKING=1& C:\\tools\\msys64\\usr\\bash -li -c "\$@"'
      export mingw64='cmd //C SET MSYSTEM=MINGW64& CHERE_INVOKING=1& C:\\tools\\msys64\\usr\\bash -li -c "\$@"'
      $msys2 pacman --sync --noconfirm --needed base base-devel msys2-devel mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
      ## Install more MSYS2 packages from https://packages.msys2.org/base here
      taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
      export MAKE=mingw32-make
    else
      export MAKE=make
    fi

install:
  - export MAKEFLAGS="-j $(nproc)"

script:
  - $MAKE CC="${CC:-gcc}$cc_append"
  - test -z "$c_tests" || $MAKE check CC="${CC:-gcc}$cc_append" STEMMING_DATA=snowball-data
  - test -z "$PYTHON"  || $MAKE check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || $MAKE check_java STEMMING_DATA=snowball-data
  - test -z "$MCS"     || $MAKE check_csharp MCS="$MCS" STEMMING_DATA=snowball-data
  - test -z "$NODE"    || $MAKE check_js     STEMMING_DATA=snowball-data
  - test -z "$RUST"    || $MAKE check_rust   STEMMING_DATA=snowball-data
  - test -z "$RUST"    || $MAKE check_rust cargoflags=--release STEMMING_DATA=snowball-data
  - test -z "$GO"      || $MAKE check_go     STEMMING_DATA=snowball-data
  - test -z "$FPC"     || $MAKE check_pascal STEMMING_DATA=snowball-data

before_cache:
  - test x$TRAVIS_OS_NAME = xwindows && $msys2 pacman --sync --clean --noconfirm

cache:
  directories:
  - $HOME/AppData/Local/Temp/chocolatey
  - /C/tools/msys64