language: minimal
#dist: trusty
matrix:
  include:
    - os: windows
      language: c
      #env: c_tests=y

before_install:
  # Try to check out a branch of the same name from the snowball-data repo
  # sibling of this snowball repo, so that PRs requiring changes to both can be
  # CI tested easily.
  #
  # If that fails, just use the standard snowball-data repo's default branch.
  - GH_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - GH_REPO_SLUG=${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}
  - GH_REPO_URL=https://github.com/${GH_REPO_SLUG%%/*}/snowball-data.git
  - echo "Trying branch $GH_BRANCH from $GH_REPO_URL"
  - git clone --depth=1 -b "$GH_BRANCH" "$GH_REPO_URL" || git clone --depth=1 https://github.com/snowballstem/snowball-data.git
  - >
    if test x$TRAVIS_OS_NAME = xwindows; then
      test -f C:/tools/msys64/msys2_shell.cmd && rm -rf C:/tools/msys64
      choco uninstall -y mingw
      choco upgrade --no-progress -y msys2
      export msys2='cmd //C RefreshEnv.cmd '
      export msys2+='& set MSYS=winsymlinks:nativestrict '
      export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
      export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
      export msys2+=" -msys2 -c "\"\$@"\" --"
      $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
      ## Install more MSYS2 packages from https://packages.msys2.org/base here
      taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
      export PATH=/C/tools/msys64/mingw64/bin:/C/tools/msys64/usr/bin:$PATH
    fi

script:
  - make CC="${CC:-gcc}$cc_append"
  - test -z "$c_tests" || make check CC="${CC:-gcc}$cc_append" STEMMING_DATA=snowball-data
  - test -z "$PYTHON" || make check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || make check_java STEMMING_DATA=snowball-data
  - test -z "$MCS" || make check_csharp MCS="$MCS" STEMMING_DATA=snowball-data
  - test -z "$NODE" || make check_js STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust STEMMING_DATA=snowball-data
  - test -z "$RUST" || make check_rust cargoflags=--release STEMMING_DATA=snowball-data
  - test -z "$GO" || make check_go STEMMING_DATA=snowball-data
  - test -z "$FPC" || make check_pascal STEMMING_DATA=snowball-data

before_cache:
  - >
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64