language: c

dist: trusty

os:
- windows

before_install:
  # Try to check out a branch of the same name from the snowball-data repo
  # sibling of this snowball repo, so that PRs requiring changes to both can be
  # CI tested easily.
  #
  # If that fails, just use the standard snowball-data repo's default branch.
  - git clone --depth=1 https://github.com/snowballstem/snowball-data.git
  - test -f C:/tools/msys64/msys2_shell.cmd && echo "msys2_shell.cmd found" || rm -rf C:/tools/msys64
  - choco uninstall -y mingw
  - choco upgrade --no-progress -y msys2
  - echo $PATH
  - export msys2='cmd //C RefreshEnv.cmd '
  #- export msys2+='& set MSYS=winsymlinks:nativestrict '
  - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
  - export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
  - export msys2+=" -msys2 -c "\"\$@"\" --"
  - export PATH=/c/tools/msys64/mingw64/bin:/c/tools/msys64/usr/bin:$PATH
  - which pacman || true
  - $msys2 pacman --sync --noconfirm --needed base base-devel msys2-devel
  #- $msys2 pacman --sync --noconfirm --needed mingw-w64-i686-toolchain mingw-w64-i686-make
  - $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-make
  - tasklist | grep -q gpg-agent && taskkill //IM gpg-agent.exe //F # https://travis-ci.community/t/4967
  - export MAKE=mingw32-make
  - $MAKE --version
  - gcc --version

install:
  - test x$NUMBER_OF_PROCESSORS = x || export MAKEFLAGS="-j $NUMBER_OF_PROCESSORS"

script:
  - $MAKE CC="${CC:-gcc}$cc_append"
  - test -z "$c_tests" || $MAKE check CC="${CC:-gcc}$cc_append" STEMMING_DATA=snowball-data
  - test -z "$PYTHON"  || $MAKE check_python python="$PYTHON" STEMMING_DATA=snowball-data
  - test -z "$JAVA" -o -z "$JAVAC" || $MAKE check_java STEMMING_DATA=snowball-data
  - test -z "$MCS"     || $MAKE check_csharp MCS="$MCS" STEMMING_DATA=snowball-data
  - test -z "$NODE"    || $MAKE check_js     STEMMING_DATA=snowball-data
  - test -z "$RUST"    || $MAKE check_rust   STEMMING_DATA=snowball-data
  - test -z "$RUST"    || $MAKE check_rust cargoflags=--release STEMMING_DATA=snowball-data
  - test -z "$GO"      || $MAKE check_go     STEMMING_DATA=snowball-data
  - test -z "$FPC"     || $MAKE check_pascal STEMMING_DATA=snowball-data

before_cache:
  - test x$TRAVIS_OS_NAME = xwindows && $msys2 pacman --sync --clean --noconfirm

cache:
  directories:
  - /C/tools/msys64
